server:
  post: 8080
  servlet:
    context-path: /tour_management

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/tour_management"
    username: root
    password: ""
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true